Some weights of the model checkpoint at google/bigbird-roberta-base were not used when initializing BigBirdModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BigBirdModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BigBirdModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
  0%|          | 0/516 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/alex/Projects/usc-research/source-exploration/tasks/quote_attribution/other_platforms/span-detection-approaches/trainer.py", line 123, in <module>
    include_nones_as_positives=data_args.include_nones_as_positives,
  File "./dataset.py", line 127, in __init__
    self.process_data_file(input_data)
  File "./dataset.py", line 161, in process_data_file
    [1] * (sent_end_tok - sent_start_tok) + \
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.22.0
Out[1]: 569
Out[3]: 'There were about 20 passengers on board of which most were of high stature , ‚Äù said <span style="font-weight: bold">Sek Wannamethee</span> , a spokesman for the Thai Foreign Ministry .'
Out[5]: 569
Out[8]: 2981
Out[9]: 2797
Out[10]: 184
Traceback (most recent call last):
  File "/Users/alex/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3396, in run_code
    async def run_code(self, code_obj, result=None, *, async_=False):
  File "<ipython-input-11-88b8d056e819>", line 1, in <module>
    doc[s_start, s_end]
TypeError: list indices must be integers or slices, not tuple
Out[12]: []
